language: php

matrix:
    include:
        - php: hhvm
        - php: 5.6
        - php: 7.0
    fast_finish: true

services: mongodb

sudo: false

before_script:
    - composer self-update
    - composer install

script:
    - phpunit
