language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.6
        - php: 7.0
    fast_finish: true

install:
    - composer --prefer-source install;

script:
    - phpunit
