language: php

php:
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.6

services: mongodb

before_script:
    - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then phpenv config-add travis.php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer self-update
    - composer install

script:
    - phpunit
