language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
  allow_failures:
    - php: 7.0

services: mongodb

before_script:
    - phpenv config-rm xdebug.ini
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install

script:
    - phpunit
