language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
  allow_failures:
    - php: 7.0

services: mongodb

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - if [[ $TRAVIS_PHP_VERSION == '7.0' ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer self-update
    - composer install

script:
    - phpunit
